version: "3.7"

services:
  app:
    container_name: walk-and-discover
    restart: always
    image: walkdiscover
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: yarn dev